import Head from "next/head"
import React from "react"
import styles from "../styles/Layout.module.scss"
import Navbar from "./Navbar"

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>FasoLara | Accueil</title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/solar.svg" />
      </Head>
      <main>
        <div className={styles.pageContent}>
          <Navbar />
          {children}
        </div>
      </main>
    </div>
  )
}

export default Layout
